<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>MDPlus.Tests</RootNamespace>
    <AssemblyName>MDPlus.Tests</AssemblyName>
    <StartupObject>MDPlus.Tests.TestRunner</StartupObject>
    <DefaultItemExcludes>$(DefaultItemExcludes);adversarial*/**;e2e/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\MDPlus.csproj" />
  </ItemGroup>

</Project>
