<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>MDPlus.Benchmarks</RootNamespace>
    <AssemblyName>MDPlus.Benchmarks</AssemblyName>
    <StartupObject>MDPlus.Benchmarks.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\MDPlus.csproj" />
  </ItemGroup>

</Project>
